In [1]:
import cv2
import numpy as np

In [12]:
img = cv2.imread('images.png',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)


In [38]:
dilation = cv2.dilate(img,kernel,iterations = 1)


-1

In [39]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)


48

In [41]:
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)


-1

In [42]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)


-1

In [30]:
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)



In [28]:
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)


In [43]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
# Rectangular Kernel
>>> cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)
# Elliptical Kernel
>>> cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)
# Cross-shaped Kernel
>>> cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)

NameError: name 'array' is not defined